### ISSUE TITLE
CBC encryption

### ISSUE THREAD

**Issue by somnial** [falsovsky/FiSH-irssi#12]
Will CBC encryption be implemented? Would be very helpful for better compatibility with other irc clients.

**Comment by kelek-** [comment]
Is there any effort from your side to implement this? Since i always have to deal with people using mIRC and their CBC fish implementation - so that would be really great to be able to keyx using CBC.

**Comment by tittof** [comment]
I started a branch https://github.com/tittof/FiSH-irssi/commits/fish2 that implements XSalsa20 with Poly1305 MAC (overhead 40 bytes).
You can switch that method off and on using /setmethod or /delmethod.

There is also a first lousy attempt to make blowfish cbc part of this plugin but I could use some help here as I'm not too interested in it.

Anyway let me know what you think.

**Comment by falsovsky** [comment]
Hi there!

CBC mode has been implemented in the cbc branch - https://github.com/falsovsky/FiSH-irssi/tree/cbc 

I tested it with mirc with fish and they can talk correctly.

**Comment by falsovsky** [comment]
@kelek- @somnial @tittof ping! Can you guys test this out?

**Comment by somnial** [comment]
Hi @falsovsky, cheers for working on this. Unfortunately, while testing it irssi crashed with what I think looks like heap corruption. I'll raise an separate issue for it.

**Comment by somnial** [comment]
On the latest cbc branch (7b987ec) cbc keyx appears to be working for me, both when I initiate and receive.

**Comment by falsovsky** [comment]
Nice! I'm also testing for a few weeks, after that I will merge it into master! Thanks for testing @somnial

**Comment by falsovsky** [comment]
Merged into master.
