### ISSUE TITLE
Prepend fish_ to config keys

### ISSUE THREAD

**Issue by tobbez** [falsovsky/FiSH-irssi#26]
Please consider adding the fish_ prefix to irssi config keys.

This would allow one to use `/set fish` to get a list of all the config keys used by the fish module.

**Comment by falsovsky** [comment]
Ok! This seems to be a good idea.

I'm going to look into it, the only problem is that it will break the current configurations that people have.

But that shoulnt be a BIG problem. :-)

**Comment by falsovsky** [comment]
It will continue as it is. Wont change this soon.
