### ISSUE TITLE
implicit declaration of ischannel

### ISSUE THREAD

**Issue by kelek-** [falsovsky/FiSH-irssi#27]
Hello,
with the latest version of your fish module I get the following error/warning during make 
`/root/sources/FiSH-irssi/src/FiSH.c: In function ‘decrypt_msg’:
/root/sources/FiSH-irssi/src/FiSH.c:235:6: warning: implicit declaration of function ‘ischannel’ [-Wimplicit-function-declaration]
  if (ischannel(*target))
      ^`
It finishes to build successfully, but whenever I try to load it, i get the following error in irssi:
`*** Irssi: Error loading module fish/fish: /usr/local/lib/irssi/modules/libfish.so: undefined symbol: ischannel`

Is this an error on my side?

**Comment by falsovsky** [comment]
I've been working on it.. and it have always been compiling without any problems.

Which distribution are you using ?

**Comment by falsovsky** [comment]
Youre using irssi from git ? It seems they removed that function from irc.h.

**Comment by falsovsky** [comment]
And it seems they now have a function called server_ischannel()

**Comment by falsovsky** [comment]
If i change the code... it will break for all the older irssi versions

**Comment by kelek-** [comment]
I see, i just successfully build it using latest stable (0.8.17) irssi. The latest git version breaks it indeed.

**Comment by falsovsky** [comment]
I'm going to try to add a fix for that, without breaking all the older versions.

**Comment by kelek-** [comment]
That would be awesome!

**Comment by falsovsky** [comment]
Just to report you that FiSH now works with the old irssi and the new from git :-)

If you have any problem with it, please reopen this! Thanks!

**Comment by Carmageddon** [comment]
This problem still exists on current version of freebsd freshports package:
https://www.freshports.org/irc/irssi-fish/
Version 1.00.r5 added on 01 Apr 2016 14:08:38 :(

How can this be fixed in the package?

**Comment by falsovsky** [comment]
@Carmageddon 
That port inst from this version of FiSH-irssi, its from the old and unmaintained version.

A few months ago I contacted the maintainer of that port, told him to use mine instead, but he didnt do anything.

Try to contact him again.

**Comment by Carmageddon** [comment]
Thanks, I messaged him too..
