### ISSUE TITLE
long key wil crash irssi

### ISSUE THREAD

**Issue by martijne** [falsovsky/FiSH-irssi#28]
A long(> 96 chars ) key wil crash irssi

for example:
```
/setkey #testchan aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

**Comment by martijne** [comment]
For fix see https://github.com/falsovsky/FiSH-irssi/pull/29

**Comment by falsovsky** [comment]
I think i fixed it.

I would like for you to test it out if you can.

```
git clone https://github.com/falsovsky/FiSH-irssi.git
cd FiSH-irssi
git checkout mallocs
```

And then build it normally

**Comment by martijne** [comment]
Sorry i was a way for a couple of day's.

I compiled this new branch en it seems to work nicely for 2 hours now
Tested on a ubuntu 15.04 x64 and Raspbian Jessie (raspbery pi 1)

**Comment by falsovsky** [comment]
I've merged this into the master.
