### ISSUE TITLE
wrong info for blow.ini

### ISSUE THREAD

**Issue by bibidinu** [falsovsky/FiSH-irssi#33]
how do I remove > prefix?
i have set on blow.ini

how do I remove>

[FiSH]
process_incoming=1
process_outgoing=1
mark_position=0
mark_encrypted=
plain_prefix="+p "
mark_broken_block=0

[net:#chan]
key=+OK 9faqY11zc810.cskJ18rM.

but still announce prefix >

**Comment by falsovsky** [comment]
Theres an option on the readme for that "mark_encrypted"

I just did "/unset mark_encrypted" it it no longer appears. Can you verify ?

**Comment by bibidinu** [comment]
ok i have read wrong txt now work bro tnx ! :dancers:
