### ISSUE TITLE
error while loading on irssi 0.8.18

### ISSUE THREAD

**Issue by saytin** [falsovsky/FiSH-irssi#34]
When trying to load fish in new irssi i get error:
 Irssi: fish/fish is ABI version 0 but Irssi is version 1, cannot load

I've compiled fish after I've compiled irssi

**Comment by falsovsky** [comment]
Youre doing something wrong. I just built irssi 0.8.18 and the latest FiSH and its working.

```
00:05 -!-  ___           _
00:05 -!- |_ _|_ _ _____(_)
00:05 -!-  | || '_(_-<_-< |
00:05 -!- |___|_| /__/__/_|
00:05 -!- Irssi v0.8.18 - http://www.irssi.org
00:05 -!- Irssi: FiSH r218-2b0c1c0 - encryption module for irssi loaded!
```

I already added support for that a few weeks ago.

**Comment by saytin** [comment]
i got libfish.so in ~/.irssi/modules. Sry for troubles.
