### ISSUE TITLE
*** glibc detected *** irssi: corrupted double-linked list: 0x09e4d538 **

### ISSUE THREAD

**Issue by RogerCageot** [falsovsky/FiSH-irssi#39]
When posting a special long ANSI line, irssi is crashing.

For info, irssi is 0.8.15 & FiSH is v1.00.

**Comment by falsovsky** [comment]
Give me an example, so that I can reproduce it

**Comment by RogerCageot** [comment]
@falsovsky : ░ ▓██▄  ▒██▒ ▓██░ ▒▒███      ▒ ▓██░ ▒▒██▀▀██▒███  ▓██    ▓██▒███      ▓██░ ██▓▒██░   ░ ▓██▄    ▒   ██░██░ ▓██▓ ░▒▓█  ▄    ░ ▓██▓ ░░▓█ ░██▒▓█  ▄▒██    ▒██▒▓█  ▄    ▒██▄█▓▒ ▒██░

**Comment by falsovsky** [comment]
Are you sure that youre using the FiSH from this repository ?

**Comment by falsovsky** [comment]
Hello ?

**Comment by falsovsky** [comment]
@RogerCageot  well ?? Is this a bug or not ?
