### ISSUE TITLE
[FEATURE-REQUEST] wait for password at startup

### ISSUE THREAD

**Issue by z0rti** [falsovsky/FiSH-irssi#40]
Hi,

when i start irssi, the module is loaded via ~/.irssi/startup file.
So i get the 'Enter password:' prompt, but in the background
irssi is connecting to the server, joining channels.
Irssi then complains 'Remove unknown settings from config file (Y/n)?' 
Because of some settings like 'mark_encrypted' which are not known, as it still waits for the PW.
Is it possible to block irssi, until the pw is entered? (like the old 0.99+0.8.17)

ciao,
Z

**Comment by falsovsky** [comment]
I cant reproduce what you say about 'Remove unknown settings from config file (Y/n)?'.

I just added a new network to irssi, and an auto join channel to that network. Enabled fish on that channel. And quit.

Added load fish to the startup file.

Everything works as expected, he connects to the network and joins the channel normally on background. No errors.

Then, when you insert the password, it starts to decrypt/encrypt the messages on the channel.

**Comment by falsovsky** [comment]
maybe a new irssi version? I'm going to update to the latest and try.

**Comment by falsovsky** [comment]
I just upgraded to irssi 0.8.20 and still nothing wrong.

I'm going to need some more info to help me reproduce.

**Comment by z0rti** [comment]
You didn't set any settings e.g. /set mark_encrypted ">> "
(don't forget to /save them)

>Then, when you insert the password, it starts to decrypt/encrypt the messages on the channel.
This is also a "problem", it doesn't decrypt the topic, because the pw is entered AFTER the chan is joined, so a /cycle is needed.

The old version i got 0.99 with irssi 0.8.17 used to block everything until the pw is entered.

**Comment by falsovsky** [comment]
Ok. I could reproduce it now!

I cant put that blocking irssi, that was a very bad thing to do.
If you loaded fish after connecting to irc, it would block all connections.

I'm going to take a look on how to fix this! Thanks for the report :)

**Comment by falsovsky** [comment]
z0rti, please update and try it out!

**Comment by z0rti** [comment]
Yep that fixed the 'Remove unknown settings from config file (Y/n)?'
Thanks ;)

**Comment by falsovsky** [comment]
I'm sorry that you were used to the lock, but that was very bad for irssi.
The current implementation is much better as it doesnt block irssi and the network.

Thank you too for reporting!
