### ISSUE TITLE
Encrypted Topic isn't decrypted AFTER fishlogin

### ISSUE THREAD

**Issue by z0rti** [falsovsky/FiSH-irssi#41]
An encrypted topic is not decrypted if i join a channel before i enter the ini password.

How to reproduce:
Join a chan with a previously encrypted topic (/topic+ foo)
Enter ini pw (/fishlogin)
See topicbar and /topic returning crypted +OK string

Fix:
Maybe update topicbar/topic content after fishlogin?

**Comment by falsovsky** [comment]
Fixed, thanks for reporting! It took two years because I didnt knew how to do it :-)
