### ISSUE TITLE
Unable to compile on Debian Stretch

### ISSUE THREAD

**Issue by Ossii** [falsovsky/FiSH-irssi#47]
/tmp/FiSH-irssi# cmake .
-- Using glib-2.0 2.50.2
-- Using OpenSSL 1.1.0c
-- irssi includes were found on /usr/include/irssi
-- The module will be installed by default to /usr/local/lib/irssi/modules
-- You can change it with 'cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .'
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/FiSH-irssi

/tmp/FiSH-irssi# make
[ 14%] Building C object src/CMakeFiles/fish.dir/base64.c.o
[ 28%] Building C object src/CMakeFiles/fish.dir/blowfish.c.o
[ 42%] Building C object src/CMakeFiles/fish.dir/inifile.c.o
[ 57%] Building C object src/CMakeFiles/fish.dir/DH1080.c.o
/tmp/FiSH-irssi/src/DH1080.c: In function ‘DH1080_Init’:
/tmp/FiSH-irssi/src/DH1080.c:46:13: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
         g_dh->p = BN_bin2bn(prime1080, DH1080_PRIME_BYTES, NULL);
             ^~
src/CMakeFiles/fish.dir/build.make:134: recipe for target 'src/CMakeFiles/fish.dir/DH1080.c.o' failed
make[2]: *** [src/CMakeFiles/fish.dir/DH1080.c.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/fish.dir/all' failed
make[1]: *** [src/CMakeFiles/fish.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ml-** [comment]
Doesn't support OpenSSL 1.1.0c yet.

See: https://github.com/falsovsky/FiSH-irssi/pull/45

Try: https://github.com/dogo42/FiSH-irssi

**Comment by falsovsky** [comment]
I already merged that PR. This is fixed.
