### ISSUE TITLE
coredump on Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by markrussinovichgithub** [falsovsky/FiSH-irssi#49]
Fresh install of Ubuntu LTS 16.04.1 LTS and followed the installation steps.
Compiling without errors.
Loading fish is succesfull (/load /home/mark/FiSH-irssi/src/libfish.so).
Entering a chan works.
/setkey #mychan key    too.
Type something, press enter, irssi crashes.

The following is what i got from a strace:

```
open("/home/mark/.irssi/blow.ini", O_RDONLY) = 5
fstat(5, {st_mode=S_IFREG|0664, st_size=58, ...}) = 0
read(5, "[network:#mychan]\nkey=+OK"..., 4096) = 58
read(5, "", 4096)                       = 0
close(5)                                = 0
open("/dev/tty", O_RDWR|O_NOCTTY|O_NONBLOCK) = 5
writev(5, [{"*** Error in `", 14}, {"irssi", 5}, {"': ", 3}, {"free(): invalid next size (fast)", 32}, {": 0x", 4}, {"000055a842693d90", 16}, {" ***\n", 5}], 7) = 79
```

Let me know if i can provide anything more.

Mark

**Comment by falsovsky** [comment]
Please try it again. Already fixed.

**Comment by markrussinovichgithub** [comment]
Yes, i can confirm it is solved.
Thanks!!
