### ISSUE TITLE
glib-2.0 missing

### ISSUE THREAD

**Issue by yabbah** [falsovsky/FiSH-irssi#50]
When i run 'cmake .' I got this: 

`@homebridge:~/FiSH-irssi$ cmake .
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking for module 'glib-2.0'
--   No package 'glib-2.0' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:23 (PKG_CHECK_MODULES)

-- Configuring incomplete, errors occurred!
See also "/home/xXXXx/FiSH-irssi/CMakeFiles/CMakeOutput.log".`

But when I then try to install it using apt I get:

`@homebridge:~/FiSH-irssi$ sudo apt-get install glib-2.0

[sudo] password for xXXXx: 
Läser paketlistor… Färdig
Bygger beroendeträd       
Läser tillståndsinformation… Färdig
Observera, väljer "libspice-client-glib-2.0-dev" för det reguljära uttrycket "glib-2.0"
Observera, väljer "libqt5glib-2.0-0" för det reguljära uttrycket "glib-2.0"
Observera, väljer "gir1.2-spice-client-glib-2.0" för det reguljära uttrycket "glib-2.0"
Observera, väljer "gir1.2-glib-2.0" för det reguljära uttrycket "glib-2.0"
Observera, väljer "libspice-client-glib-2.0-1" för det reguljära uttrycket "glib-2.0"
Observera, väljer "libspice-client-glib-2.0-8" för det reguljära uttrycket "glib-2.0"
Observera, väljer "libqtglib-2.0-0" för det reguljära uttrycket "glib-2.0"
gir1.2-glib-2.0 is already the newest version (1.46.0-3ubuntu1).
gir1.2-spice-client-glib-2.0 is already the newest version (0.30-1).
libqt5glib-2.0-0 is already the newest version (1.2.0-3).
libqtglib-2.0-0 is already the newest version (1.2.0-3).
libspice-client-glib-2.0-8 is already the newest version (0.30-1).
libspice-client-glib-2.0-dev is already the newest version (0.30-1).
0 att uppgradera, 0 att nyinstallera, 0 att ta bort och 96 att inte uppgradera.`

Any idea?!

**Comment by falsovsky** [comment]
The package is something like: glib2.0-dev

do a apt-cache search glib|grep -dev

**Comment by yabbah** [comment]
Thank you, libglib2.0-dev was the correct packagesname. :)

**Comment by falsovsky** [comment]
I updated the documentation with that info. Missed that one :)
