### ISSUE TITLE
keyx with people having [ and ] in their name causing error

### ISSUE THREAD

**Issue by kelek-** [falsovsky/FiSH-irssi#53]
Hello,
irssi throws an error, when trying to /keyx with a person, who is named [name].
This is the error shown:
Irssi: critical g_key_file_set_value: assertion 'g_key_file_is_group_name (group_name)' failed

**Comment by falsovsky** [comment]
I can confirm this bug exists.

I'm going to take a look into it. Lets hope its not a glib limitation.

**Comment by falsovsky** [comment]
I fixed it with a workaround for glib. Please test it out.

**Comment by falsovsky** [comment]
ping?

**Comment by falsovsky** [comment]
ping

**Comment by kelek-** [comment]
Thank you it works as expected.
Simply forgot to reply, my bad.

Thanks for the fix!
