### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by warsylep** [falsovsky/FiSH-irssi#54]
This addon doesn't works in mIRC 7.2 - Windows 7 x64, plz fix it with a whitelist.

                    _..._
                 .-'     '-.
                /     _    _\
               /':.  (o)  /__)
              /':. .,_    |  |
             |': ; /  \   /_/
             /  ;  `"`"    }
            ; ':.,         {
           /      ;        }
          ; '::.   ;\/\ /\ {
         |.      ':. ;``"``\
        / '::'::'    /      ;
       |':::' '::'  /       |
       \   '::' _.-`;       ;
       /`-..--;` ;  |       |
      ;  ;  ;  ;  ; |       |
      ; ;  ;  ; ;  ;        /        ,--.........,
      |; ;  ;  ;  ;/       ;       .'           -='.
      | ;  ;  ; ; /       /       .\               '
      |  ;   ;  /`      .\   _,=="  \             .'
      \;  ; ; .'. _  ,_'\.\~"   //`. \          .'
      |  ;  .___~' \ \- | |    /,\ `  \      ..'
    ~ ; ; ;/  =="'' |`| | |       =="''\.==''
    ~ /; ;/=""      |`| |`|   ==="`
    ~..==`     \\   |`| / /=="`
     ~` ~      /,\ / /= )")
    ~ ~~         _')")  
    ~ ~   _,=~";`
    ~  =~"|;  ;|       Penisbird
     ~  ~ | ;  |       =========
  ~ ~     |;|\ |
          |/  \|

**Comment by falsovsky** [comment]
lol...
