### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by nik-k** [falsovsky/FiSH-irssi#55]
I'm on gentoo 64-bit:

`[ 14%] Building C object CMakeFiles/fish.dir/base64.o
[ 28%] Building C object CMakeFiles/fish.dir/blowfish.o
/home/chef/built/FiSH-irssi/src/blowfish.c:8:12: Fehler: unbekannter Typname: »uint32_t«
     static uint32_t
            ^
/home/chef/built/FiSH-irssi/src/blowfish.c:20:12: Fehler: unbekannter Typname: »uint32_t«
     static uint32_t
            ^
/home/chef/built/FiSH-irssi/src/blowfish.c: In Funktion »load32_be«:
/home/chef/built/FiSH-irssi/src/blowfish.c:24:13: Fehler: »uint32_t« nicht deklariert (erste Benutzung in dieser Funktion)
     return (uint32_t) in[0] << 24 |
             ^
/home/chef/built/FiSH-irssi/src/blowfish.c:24:13: Anmerkung: jeder nicht deklarierte Bezeichner wird nur einmal für jede Funktion, in der er vorkommt, gemeldet
/home/chef/built/FiSH-irssi/src/blowfish.c:24:23: Fehler: expected »;« before »in«
     return (uint32_t) in[0] << 24 |
                       ^
/home/chef/built/FiSH-irssi/src/blowfish.c: Auf höchster Ebene:
/home/chef/built/FiSH-irssi/src/blowfish.c:29:22: Fehler: unbekannter Typname: »uint32_t«
 store32_be (void *p, uint32_t v)
                      ^
/home/chef/built/FiSH-irssi/src/blowfish.c: In Funktion »encrypt_string«:
/home/chef/built/FiSH-irssi/src/blowfish.c:53:9: Fehler: unbekannter Typname: »uint32_t«
         uint32_t v;
         ^
/home/chef/built/FiSH-irssi/src/blowfish.c: In Funktion »decrypt_string«:
/home/chef/built/FiSH-irssi/src/blowfish.c:83:5: Fehler: unbekannter Typname: »uint32_t«
     uint32_t v;
     ^
/home/chef/built/FiSH-irssi/src/blowfish.c:101:9: Warnung: Implizite Deklaration der Funktion »store32_be« [-Wimplicit-function-declaration]
         store32_be (block + 4, v);
         ^
make[2]: *** [CMakeFiles/fish.dir/build.make:87: CMakeFiles/fish.dir/blowfish.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/fish.dir/all] Fehler 2
make: *** [Makefile:128: all] Fehler 2
I'm on gentoo 64-bit:

[ 14%] Building C object CMakeFiles/fish.dir/base64.o
[ 28%] Building C object CMakeFiles/fish.dir/blowfish.o
/home/chef/built/FiSH-irssi/src/blowfish.c:8:12: Fehler: unbekannter Typname: »uint32_t«
     static uint32_t
            ^
/home/chef/built/FiSH-irssi/src/blowfish.c:20:12: Fehler: unbekannter Typname: »uint32_t«
     static uint32_t
            ^
/home/chef/built/FiSH-irssi/src/blowfish.c: In Funktion »load32_be«:
/home/chef/built/FiSH-irssi/src/blowfish.c:24:13: Fehler: »uint32_t« nicht deklariert (erste Benutzung in dieser Funktion)
     return (uint32_t) in[0] << 24 |
             ^
/home/chef/built/FiSH-irssi/src/blowfish.c:24:13: Anmerkung: jeder nicht deklarierte Bezeichner wird nur einmal für jede Funktion, in der er vorkommt, gemeldet
/home/chef/built/FiSH-irssi/src/blowfish.c:24:23: Fehler: expected »;« before »in«
     return (uint32_t) in[0] << 24 |
                       ^
/home/chef/built/FiSH-irssi/src/blowfish.c: Auf höchster Ebene:
/home/chef/built/FiSH-irssi/src/blowfish.c:29:22: Fehler: unbekannter Typname: »uint32_t«
 store32_be (void *p, uint32_t v)
                      ^
/home/chef/built/FiSH-irssi/src/blowfish.c: In Funktion »encrypt_string«:
/home/chef/built/FiSH-irssi/src/blowfish.c:53:9: Fehler: unbekannter Typname: »uint32_t«
         uint32_t v;
         ^
/home/chef/built/FiSH-irssi/src/blowfish.c: In Funktion »decrypt_string«:
/home/chef/built/FiSH-irssi/src/blowfish.c:83:5: Fehler: unbekannter Typname: »uint32_t«
     uint32_t v;
     ^
/home/chef/built/FiSH-irssi/src/blowfish.c:101:9: Warnung: Implizite Deklaration der Funktion »store32_be« [-Wimplicit-function-declaration]
         store32_be (block + 4, v);
         ^
make[2]: *** [CMakeFiles/fish.dir/build.make:87: CMakeFiles/fish.dir/blowfish.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/fish.dir/all] Fehler 2
make: *** [Makefile:128: all] Fehler 2`

**Comment by falsovsky** [comment]
No it doesnt, as I run Gentoo 64bits.

Please show what did you run.

**Comment by falsovsky** [comment]
```
falso@fishy ~/test $ uname -a
Linux fishy 4.10.0-gentoo #1 SMP Tue Feb 21 10:27:11 WET 2017 x86_64 Intel(R) Core(TM)2 Quad CPU Q6600 @ 2.40GHz GenuineIntel GNU/Linux
falso@fishy ~/test $ git clone https://github.com/falsovsky/FiSH-irssi.git
Cloning into 'FiSH-irssi'...
remote: Counting objects: 1637, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1637 (delta 0), reused 0 (delta 0), pack-reused 1631
Receiving objects: 100% (1637/1637), 671.81 KiB | 876.00 KiB/s, done.
Resolving deltas: 100% (1054/1054), done.
falso@fishy ~/test $ cd FiSH-irssi/
falso@fishy ~/test/FiSH-irssi $ cmake .
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.50.3
-- Using glib-2.0 2.50.3
-- Checking for module 'openssl'
--   Found openssl, version 1.0.2k
-- Using OpenSSL 1.0.2k
-- irssi includes were found on /usr/include/irssi
-- The module will be installed by default to /usr/local/lib/irssi/modules
-- You can change it with 'cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .'
-- Found Git: /usr/bin/git (found version "2.11.1")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/falso/test/FiSH-irssi
falso@fishy ~/test/FiSH-irssi $ make
Scanning dependencies of target fish
[ 14%] Building C object src/CMakeFiles/fish.dir/base64.c.o
[ 28%] Building C object src/CMakeFiles/fish.dir/blowfish.c.o
[ 42%] Building C object src/CMakeFiles/fish.dir/inifile.c.o
[ 57%] Building C object src/CMakeFiles/fish.dir/DH1080.c.o
[ 71%] Building C object src/CMakeFiles/fish.dir/FiSH.c.o
[ 85%] Building C object src/CMakeFiles/fish.dir/password.c.o
[100%] Linking C shared module libfish.so
[100%] Built target fish
falso@fishy ~/test/FiSH-irssi $
```

**Comment by falsovsky** [comment]
ping
