### ISSUE TITLE
fish/core is ABI version 0 but Irssi is version 7, cannot load

### ISSUE THREAD

**Issue by vgropp** [falsovsky/FiSH-irssi#57]
Hi,

im running Irssi v1.0.2-1 from debian sid, i install irssi-dev and those includes are found in /usr/include/irssi (checked by removing it and then compile fails, cmake reports /usr/include/irssi as success though). 

I double checked it on a clean debian sid and get the exact same error while loading in irssi:

18:32:45 -!- Irssi v1.0.2-1 - http://www.irssi.org
18:32:48 -!- Irssi: fish/core is ABI version 0 but Irssi is version 7, cannot load
18:32:48 -!- Irssi: fish/core is ABI version 0 but Irssi is version 7, cannot load

thanks for your help

**Comment by falsovsky** [comment]
I just tried it on a Debian Sid and it worked correctly.

You probably have two versions of the irssi headers installed

**Comment by vgropp** [comment]
thanks, that solved the issue, i was using /load fish using a symlink from /usr/lib/x86_64-linux-gnu/irssi/modules/ to /usr/lib/irssi/modules/libfish.so. Any idea how to fix this issue instead of using full path? Im not sure i can remember it next time starting irssi ;-)

**Comment by falsovsky** [comment]
Well

for now you can:

echo "load /usr/lib/irssi/modules/libfish.so" >> /home/username/.irssi/startup

**Comment by falsovsky** [comment]
@vgropp I'll try to check if the modules path is specified in any irssi header and try to use that!

**Comment by vgropp** [comment]
Thanks alot. And there seem to be an issue with cmake. After removing (rm -r /usr/include/irssi) the headers it still outputs: -- irssi includes were found on /usr/include/irssi
Its a bit misleading, but as it is working with your help im closing this issue

**Comment by falsovsky** [comment]
YEs you need to remove the cmake cache.
