### ISSUE TITLE
Mac OSX install instructions

### ISSUE THREAD

**Issue by laurentperez** [falsovsky/FiSH-irssi#58]
Hi

I had to compile fish under Mac OSX, maybe the following instructions should be added to the homepage

`first, install MacPorts from https://www.macports.org/`
`sudo port install glib2 libsodium`

Compilation is working fine. You need macports because glib libs are not found when using brew.

**Comment by falsovsky** [comment]
This doesnt require libsodium.

**Comment by laurentperez** [comment]
my bad, it was required by the https://github.com/tittof/FiSH-irssi/commit/d9e2db87690a947d14a5036a38035050e68555c5 forked at https://github.com/falsovsky/FiSH-irssi/issues/12#issuecomment-279146596. If it is ever merged to add CBC support it may be useful.

still, the glib2 installation thru macport is required.

**Comment by qpenko** [comment]
I have documented a set of steps I recently took in order to build FiSH-irssi under macOS Sierra:

1. Use Homebrew to install following packages:
   `cmake, irssi, openssl, pkg-config`
   
   using command: `brew install <package>`

2. Use MacPorts to install following packages:
   `glib2`

   using command: `sudo port -t install glib2`

3. `git clone https://github.com/falsovsky/FiSH-irssi.git`
4. `cd FiSH-irssi`
5. `cmake -DOPENSSL_INCLUDE_DIRS=/usr/local/opt/openssl/include -DOPENSSL_LIBRARY_DIRS=/usr/local/opt/openssl/lib .`
6. `make`
7. `make install`

**Comment by potem** [comment]
Can you help me figure this OpenSSL Problem out?

    make -DOPENSSL_INCLUDE_DIRS=/usr/local/opt/openssl/include -DOPENSSL_LIBRARY_DIRS=/usr/local/opt/openssl/lib .
    -- Using glib-2.0 2.54.3
    -- Checking for module 'openssl'
    --   No package 'openssl' found
    CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
    Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:31 (PKG_CHECK_MODULES)


    -- Configuring incomplete, errors occurred!
See also "/Users/x/FiSH-irssi/CMakeFiles/CMakeOutput.log".

**Comment by falsovsky** [comment]
Did you run the instructions by @qpenko  ?

**Comment by xieem** [comment]
@falsovsky I ran the instructions by @qpenko and I have the same errors as @potem 

-- Using glib-2.0 2.54.3
-- Checking for module 'openssl'
--   No package 'openssl' found
CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:31 (PKG_CHECK_MODULES)
-- Configuring incomplete, errors occurred!

**Comment by falsovsky** [comment]
I dont have an OSX computer to help you out.

**Comment by xieem** [comment]
That’s a bummer 

Maybe your friend will be able to help us out.

------------------------------------------------------
Maxime Witters
Entrepreneur
Belgian located in Poland

**Comment by nubje** [comment]
> @falsovsky I ran the instructions by @qpenko and I have the same errors as @potem
> 
> -- Using glib-2.0 2.54.3
> -- Checking for module 'openssl'
> -- No package 'openssl' found
> CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPkgConfig.cmake:415 (message):
> A required package was not found
> Call Stack (most recent call first):
> /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
> CMakeLists.txt:31 (PKG_CHECK_MODULES)
> -- Configuring incomplete, errors occurred!

I was able to get this to work by running `export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig` before running the cmake.

**Comment by tsjk** [comment]
The following seems to work:

```
$ cat /usr/local/macports/ports/irc/irssi-mod-fish-devel/Portfile
# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4

PortSystem          1.0
PortGroup           cmake 1.1
PortGroup           github 1.0

github.setup        falsovsky FiSH-irssi b208db573b133e3832372177ed2238d54a0b0ff0
version             2019-05-05
categories          net chat devel
platforms           darwin
license             GPL-3
maintainers         nomaintainer
description         FiSH is an encryption add-on module for irssi
long_description    FiSH is an encryption add-on module for irssi. \
                    Uses the Blowfish cipher to encrypt private and public messages in ECB or CBC modes, using a specified key. \
                    It also includes a secure Diffie-Hellman key exchange for private chat.

checksums           rmd160  6a450aec7534ed018c9e78f0a840c1154b1b5036 \
                    sha256  8f4afc1bff98efe65251429c68922aa86889bc1a068d3fa7638c419e23ab5396 \
                    size    21838

depends_build-append    port:pkgconfig \
                        port:glib2 \
                        port:irssi \
                        port:openssl

depends_run-append      port:glib2 \
                        port:irssi \
                        port:openssl

configure.args-append   -DIRSSI_INCLUDE_DIR:PATH=${prefix}/include/irssi/```
