### ISSUE TITLE
Irssi version mismatch

### ISSUE THREAD

**Issue by f1reflyyyylmao** [falsovsky/FiSH-irssi#60]
After the latest update of irssi on my gnu/linux box the plugin doesn't load anymore. The error says
`Irssi: fish/fish is ABI version 7 but Irssi is version 13, cannot load`
I think it's a very straightforward message. I'd be happy if someone else could take care of this, as I don't know enough c to do it.

**Comment by falsovsky** [comment]
The module needs to be recompiled every time you update irssi.

**Comment by for-coursera** [comment]
> The module needs to be recompiled every time you update irssi.

Sorry for replying to an old issue but how to build the module together with the development versions of irssi, when compiling irssi from the source? I.e., when irssi-dev package is not available?

**Comment by falsovsky** [comment]
Did you read the message from CMake?

> IF(NOT IRSSI_INCLUDE_PATH)
>     MESSAGE(SEND_ERROR "Could not detect the irssi include files. Please run:\n# cmake -DIRSSI_INCLUDE_DIR:PATH=/path/to/irssi/includes .")
>     RETURN()
> ENDIF()

**Comment by for-coursera** [comment]
It's not that simple, sadly. 

Thanks to `DIRSSI_INCLUDE_DIR`, `C_INCLUDES` in `src/CMakeFiles/fish.dir/flags.make` are indeed set to all the correct paths. However, then I get this:

    [ 75%] Building C object src/CMakeFiles/fish.dir/FiSH.c.o
    In file included from MY-BUILD-PATH/FiSH-irssi/src/module.h:5,
                     from MY-BUILD-PATH/FiSH-irssi/src/FiSH.h:10,
                     from MY-BUILD-PATH/FiSH-irssi/src/FiSH.c:1:
    MY-CUSTOM-IRSSI-INSTALL-PATH/include/irssi/src/common.h:14:10: fatal error: irssi/irssi-config.h: No such file or directory
       14 | #include <irssi/irssi-config.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[2]: *** [src/CMakeFiles/fish.dir/build.make:146: src/CMakeFiles/fish.dir/FiSH.c.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:98: src/CMakeFiles/fish.dir/all] Error 2
    make: *** [Makefile:136: all] Error 2

It's not, it seems, FISH-irssi's fault, and yet, I can't build it cleanly. Sure, I can symlink `MY-CUSTOM-IRSSI-INSTALL-PATH/include/irssi/` to `/usr/include/irssi` but maybe there's a better way?

**Comment by falsovsky** [comment]
Did you already built irssi in that custom directory ? irssi-config.h was generated during the build.

I haven't tested this in recent Irssi, since they changed to Meson, they probably changed something on the includes.

**Comment by for-coursera** [comment]
> Did you already built irssi in that custom directory 

Yep.

To reproduce:

  - `git clone https://codeberg.org/irssi/irssi` (or download and extract [1.4.5](https://codeberg.org/irssi/irssi/releases/download/1.4.5/irssi-1.4.5.tar.xz))
  - `meson Build . -Dprefix=MY-CUSTOM-IRSSI-INSTALL-PATH`
  - `ninja -C Build install`
  - `git clone https://github.com/falsovsky/FiSH-irssi`
  - `cmake -DIRSSI_INCLUDE_DIR:PATH=MY-CUSTOM-IRSSI-INSTALL-PATH/include/irssi/`
  - `make`
  - The above error.

Any help or hint is appreciated :)

**Comment by falsovsky** [comment]
You're clearly wasting my time, because you're not reading anything.

$  find .|grep irssi-config.h
./Build/irssi/irssi-config.h
./Build/irssi-config.h

Set the irssi path to the Build directory of irssi source.

**Comment by for-coursera** [comment]
> Set the irssi path to the Build directory of irssi source.

Which will result in another error. So much on wasting *my* time :)

(And here I'm asking if there's a better way than a plain symlinking...:))

**Comment by falsovsky** [comment]
> Which will result in another error. So much on wasting my time :)

**/me grabs the crystal ball** 

Works on my side as I told you. At least it builds. 
If it works i'm not sure, because I haven't migrated this to OpenSSL 3x

```
mkdir zzz
cd zzz

git clone https://codeberg.org/irssi/irssi
cd irssi
meson Build
ninja -C Build

cd ..

git clone https://github.com/falsovsky/FiSH-irssi
cd FiSH-irssi
cmake -DIRSSI_INCLUDE_DIR:PATH=../irssi/Build .
make
```

**Comment by for-coursera** [comment]
Exactly this script leads to this error for me (as I said above):

    [ 75%] Building C object src/CMakeFiles/fish.dir/FiSH.c.o
    In file included from SOME-PATH/zzz/FiSH-irssi/src/FiSH.h:10,
                     from SOME-PATH/zzz/FiSH-irssi/src/FiSH.c:1:
    SOME-PATH/zzz/FiSH-irssi/src/module.h:5:10: fatal error: common.h: No such file or directory
        5 | #include <common.h>
          |          ^~~~~~~~~~
    compilation terminated.
    make[2]: *** [src/CMakeFiles/fish.dir/build.make:146: src/CMakeFiles/fish.dir/FiSH.c.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:98: src/CMakeFiles/fish.dir/all] Error 2
    make: *** [Makefile:136: all] Error 2

**Comment by falsovsky** [comment]
Works on my side.
