### ISSUE TITLE
Segfault if password is entered but not set

### ISSUE THREAD

**Issue by aksr** [falsovsky/FiSH-irssi#62]
1. `irssi`
2. `/load fish`
3. `/fishlogin`
4. *Enter some random password* and press `Enter`.

``free(): invalid next size (fast)``
``Aborted (core dumped)``

**Arch Linux**, irssi **1.1.1 (20180213 1256)**, FiSH-irssi **266.8418ac3**

**Comment by falsovsky** [comment]
Thanks for the report. Fixed.
