### ISSUE TITLE
keyx ecb mode broken

### ISSUE THREAD

**Issue by BakasuraRCE** [falsovsky/FiSH-irssi#67]
When you do /keyx -ecb the first time with other person will be OK, after if you do /keyx it add "cbc=1" in blow.ini, and then if do /keyx -ecb the blow.ini is not updated

**Comment by falsovsky** [comment]
Hi,

Im trying to reproduce it, are both clients with FiSH-irssi ? Latest version?

**Comment by falsovsky** [comment]
@BakasuraRCE Its fixed, make sure that both clients update.
