### ISSUE TITLE
warnings after upgrading to debian buster, irssi 1.2.2

### ISSUE THREAD

**Issue by ossii79** [falsovsky/FiSH-irssi#69]
After doing a system upgrade to Debian Buster, along with compiling irssi1.2.2 and a fresh cloned FiSH-irssi I suddenly get an openssl warning after each private message (and only there).

Warnings states:
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.

Debian 10 - 64bit
irssi 1.2.2 from irssi.org
-- Using glib-2.0 2.58.3
-- Using OpenSSL 1.1.1c

**Comment by falsovsky** [comment]
Thanks for the report!
I'm going to install Debian 10 on a VM to try to reproduce it.

**Comment by falsovsky** [comment]
Hi there @ossii79 

I just installed a Debian 10 64bit VM. Built irssi-1.2.2 and get got FiSH-irssi from git.
Everything works correctly, no messages.

I did a bit of search, and in my findings that error is from the **openssl** program for the console.
https://github.com/openssl/openssl/blob/8ed7bbb411d2a9e0edef928958ad955e0be3d6dd/apps/enc.c#L481
FiSH-irssi doesn't call **openssl** directly, it uses it as a library. Are you sure you're using this plugin? Probably you're using some version of FiSH in perl that executes openssl. Or another script?

Check the output of **/script** in irssi.

**Comment by ossii79** [comment]
071957  Unloaded module fish/core
072028  FiSH r301-1171606 - encryption module for irssi loaded!
072028  URL: https://github.com/falsovsky/FiSH-irssi
072028  Try /helpfish or /fishhelp for a short command overview
072028  FiSH: Current blow.ini is password protected.
072028  Loaded module fish/core
072035  FiSH: Correct blow.ini password entered, lets go!

When you mention it being something else it does hit me that I have irssinotifier running.
Which basicaly is a frontend to take my messages and send them to my phone, only other script that reads and does something with my messages.
I'll test with remoiving that and see.

Thanks for the quick test and report! 👍

**Comment by ossii79** [comment]
Confirmed, after updating to latest version of irssinotifier (https://github.com/murgo/IrssiNotifier/blob/master/Irssi/irssinotifier.pl) it all works ok now.
Thanks for putting me on the right track @falsovsky

**Comment by falsovsky** [comment]
No problem @ossii79 . Glad I could help.
