### ISSUE TITLE
Impossible to distinguish /me from /me+

### ISSUE THREAD

**Issue by hazaelsan** [falsovsky/FiSH-irssi#72]
```
/me test
[11:38:44]  * hazael test
/me+ foo bar baz
[11:38:46]  * hazael test
```

Which makes is impossible to tell whether I used `/me` or `/me+`.  FiSH should also add a `> ` prefix to encrypted actions.

**Comment by hazaelsan** [comment]
`/notice` and `/notice+` are in the same boat.

**Comment by falsovsky** [comment]
Awesome find @hazaelsan 

I'm going to look into this, thanks for reporting!

**Comment by falsovsky** [comment]
Hi there @hazaelsan !

Willing to try https://github.com/falsovsky/FiSH-irssi/tree/missing_prefix ?

**Comment by hazaelsan** [comment]
That works, thanks!

**Comment by falsovsky** [comment]
Merged into master.
