### ISSUE TITLE
Port to Hexchat ?

### ISSUE THREAD

**Issue by kayfab3** [falsovsky/FiSH-irssi#76]
Is this something that you might be interested in offering?

The current fish implementation in hexchat has bugs, is missing features, and the third party developer has not been active the past year.

**Comment by hugopeixoto** [comment]
Hi there :wave: This project is focused on irssi. Porting it would mean rewriting most of the code, and none of the developers use hexchat, so there's no motivation for us to work on it.

I recommend that you find someone that uses hexchat to fork the existing implementation and continue working on it.

**Comment by kayfab3** [comment]
Hi

I'm aware FiSH-irssi was developed for irssi.  

To summarize Hexchat is in short supply of developers and even less expertise developing encryption modules.

The original FISH project (fish.secure.la)  is offline and long since deprecated, but when it started the dev supported mIRC, xchat, and irssi.   It's been nearly a decade since that project ended and various client focused projects appeared.

In the case of Hexchat, about 7 years ago FiSHLiM was developed outside the project.  The developer then abandoned it. The code was merged into Hexchat despite bugs and missing features.  Further development and bugfixes for the module effectively ceased for years.

Two years ago BakasuraRCE refactored the FiSHLiM code, introduced some features and then submitted a pull request..  One year ago (Sep 2020)  that code was merged into Hexchat master.  

BakasuraRCE may have lost interest and has not responded to recent bug tickets open in Oct 2021.

Bugs in the refactored FiSHLiM went largely unnoticed as most users do not compile and TingPing the  lead dev and maintainer of Hexchat did not offer a new version of Hexchat between Dec 2019 - Oct 2021.  Hexchat 2.16.0 was released this month.

As of Oct 1, 2021 Tingping announced he no longer has time to maintain Hexchat.

**Comment by kayfab3** [comment]
Hi @hugopeixoto

I'm aware FiSH-irssi was developed for irssi.  

To summarize Hexchat is in short supply of developers and even less with experience developing encryption modules.

The original FISH project (fish.secure.la)  is offline and long since deprecated, but when it started the dev supported mIRC, xchat, and irssi.   It's been nearly a decade since that project ended and various client focused projects appeared.

In the case of Hexchat, about 7 years ago FiSHLiM was developed outside the project.  The developer then abandoned it. The code was merged into Hexchat despite bugs and missing features.  Further development and bugfixes for the module effectively ceased for years.

Two years ago BakasuraRCE refactored the FiSHLiM code, introduced some features and then submitted a pull request..  One year ago (Sep 2020)  that code was merged into Hexchat master.  

BakasuraRCE may have lost interest and has not responded to recent bug tickets open in Oct 2021.

Bugs in the refactored FiSHLiM went largely unnoticed as most users do not compile and TingPing the  lead dev and maintainer of Hexchat did not offer a new version of Hexchat between Dec 2019 - Oct 2021.  Hexchat 2.16.0 was released this month.

As of Oct 1, 2021 Tingping announced he no longer has time to maintain Hexchat.
