### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by viric** [falsovsky/FiSH-irssi#9]
Hello,

maybe I miss something evident, but I can't find any license next to the source. Is there any in particular, or we should assume a default copyright?

**Comment by falsovsky** [comment]
I'm thinking of changing the license to CC0 - https://creativecommons.org/publicdomain/zero/1.0/

Anyone agaisnt this?

**Comment by pedrompcaetano** [comment]
Please do and close this ancient issue :-)
